# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .annotation import Annotation
from .function_call import FunctionCall
from .chat_completion_audio import ChatCompletionAudio
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall
from .chat_completion_message_custom_tool_call import ChatCompletionMessageCustomToolCall

__all__ = ["ChatCompletionMessage", "ToolCall"]

ToolCall: TypeAlias = Annotated[
    Union[ChatCompletionMessageToolCall, ChatCompletionMessageCustomToolCall], PropertyInfo(discriminator="type")
]


class ChatCompletionMessage(BaseModel):
    """A chat completion message generated by the model.

    Fields:
    - content (required): str | None
    - refusal (required): str | None
    - tool_calls (optional): ChatCompletionMessageToolCalls
    - annotations (optional): list[AnnotationsItem]
    - role (required): Literal["assistant"]
    - function_call (optional): FunctionCall
    - audio (optional): Audio | None
    """

    content: Optional[str] = None
    """The contents of the message."""

    refusal: Optional[str] = None
    """The refusal message generated by the model."""

    role: Literal["assistant"]
    """The role of the author of this message."""

    annotations: Optional[List[Annotation]] = None
    """
    Annotations for the message, when applicable, as when using the
    [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
    """

    audio: Optional[ChatCompletionAudio] = None
    """
    If the audio output modality is requested, this object contains data about the
    audio response from the model.
    [Learn more](https://platform.openai.com/docs/guides/audio).

    Fields:

    - id (required): str
    - expires_at (required): int
    - data (required): str
    - transcript (required): str
    """

    function_call: Optional[FunctionCall] = None
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.
    """

    tool_calls: Optional[List[ToolCall]] = None
    """The tool calls generated by the model, such as function calls."""
