# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .chat_completion_audio_param import ChatCompletionAudioParam
from .choice_delta_tool_call_function_param import ChoiceDeltaToolCallFunctionParam
from .chat_completion_content_part_text_param import ChatCompletionContentPartTextParam
from .chat_completion_content_part_refusal_param import ChatCompletionContentPartRefusalParam

__all__ = [
    "ChatCompletionAssistantMessageParam",
    "ContentChatCompletionRequestAssistantMessageContentArray",
    "FunctionCall",
    "ToolCall",
    "ToolCallChatCompletionMessageToolCallInput",
    "ToolCallChatCompletionMessageCustomToolCallInput",
    "ToolCallChatCompletionMessageCustomToolCallInputCustom",
]

ContentChatCompletionRequestAssistantMessageContentArray: TypeAlias = Union[
    ChatCompletionContentPartTextParam, ChatCompletionContentPartRefusalParam
]


class FunctionCall(TypedDict, total=False):
    arguments: Required[str]
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: Required[str]
    """The name of the function to call."""


class ToolCallChatCompletionMessageToolCallInput(TypedDict, total=False):
    id: Required[str]
    """The ID of the tool call."""

    function: Required[ChoiceDeltaToolCallFunctionParam]
    """The function that the model called."""

    type: Required[Literal["function"]]
    """The type of the tool. Currently, only `function` is supported."""


class ToolCallChatCompletionMessageCustomToolCallInputCustom(TypedDict, total=False):
    input: Required[str]
    """The input for the custom tool call generated by the model."""

    name: Required[str]
    """The name of the custom tool to call."""


class ToolCallChatCompletionMessageCustomToolCallInput(TypedDict, total=False):
    id: Required[str]
    """The ID of the tool call."""

    custom: Required[ToolCallChatCompletionMessageCustomToolCallInputCustom]
    """The custom tool that the model called."""

    type: Required[Literal["custom"]]
    """The type of the tool. Always `custom`."""


ToolCall: TypeAlias = Union[
    ToolCallChatCompletionMessageToolCallInput, ToolCallChatCompletionMessageCustomToolCallInput
]


class ChatCompletionAssistantMessageParam(TypedDict, total=False):
    role: Required[Literal["assistant"]]
    """The role of the messages author, in this case `assistant`."""

    audio: Optional[ChatCompletionAudioParam]
    """
    Data about a previous audio response from the model.
    [Learn more](https://platform.openai.com/docs/guides/audio).

    Fields:

    - id (required): str
    """

    content: Union[str, Iterable[ContentChatCompletionRequestAssistantMessageContentArray], None]
    """The contents of the assistant message.

    Required unless `tool_calls` or `function_call` is specified.
    """

    function_call: Optional[FunctionCall]
    """Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the
    model.

    Fields:

    - arguments (required): str
    - name (required): str
    """

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """

    refusal: Optional[str]
    """The refusal message by the assistant."""

    tool_calls: Iterable[ToolCall]
    """The tool calls generated by the model, such as function calls."""
