# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing_extensions import Required, TypedDict

__all__ = ["ChoiceDeltaToolCallFunctionParam"]


class ChoiceDeltaToolCallFunctionParam(TypedDict, total=False):
    """The function that the model called.

    Fields:
    - name (required): str
    - arguments (required): str
    """

    arguments: Required[str]
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: Required[str]
    """The name of the function to call."""
